"use client";

import { useState } from "react";
import { product } from "@/lib/marketing/product";
import styles from "./website.module.css";

const rupees = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
const personas = [
  { name: "Founder / Trustee", title: "A bigger vision.\nA clearer picture.", text: "Bring school operations into one connected system. Understand the day, ask better questions, and plan growth with a predictable software budget.", points: ["School and branch reporting", "Attendance, learning and fee signals", "A flat-license pricing proposal"], label: "YOUR SCHOOL, AT A GLANCE", metrics: [["Students", "1,248"], ["Attendance", "96.4%"], ["Open invoices", "32"]], rows: [["Attendance submitted", "18 / 20 classes"], ["Learning evidence", "Ready to review"], ["Leave requests", "4 awaiting review"]] },
  { name: "Principal", title: "Less chasing.\nMore teaching.", text: "Give teachers a daily workspace that connects their timetable, class diary, homework, assessments and formal academic records. Keep the work moving without another spreadsheet.", points: ["Role-specific progress dashboards", "Reusable class diaries and fast marks entry", "Reviewed report cards and transcripts"], label: "TEACHER TODAY", metrics: [["Periods today", "6"], ["Homework", "3"], ["Diary drafts", "2"]], rows: [["Grade 8 · Mathematics", "09:00–09:45"], ["Grade 9 · Algebra homework", "Published"], ["Term report cards", "Ready for review"]] },
  { name: "IT & Admin", title: "Connected work.\nFewer loose ends.", text: "Manage people, permissions and school operations in one place. Clear access boundaries and recorded changes help your team stay accountable.", points: ["Role-aware access and school data isolation", "CSV student import", "Audit events and incident triage"], label: "OPERATIONS WORKSPACE", metrics: [["User roles", "7"], ["Imports", "CSV"], ["Access", "Scoped"]], rows: [["Student directory", "Import & manage"], ["School transport", "Routes & stops"], ["Change history", "Audit events"]] },
];
const articles = [
  { title: "What does growth do to your software bill?", tag: "THE PRICING QUESTION", text: "Multiply your total students by the monthly per-student rate, then by 12. Repeat for the size you expect to reach. Compare that with the full cost of a flat license, including hosting, implementation and support. A flat fee is not automatically cheaper at every school size; the crossover matters." },
  { title: "One trust. How many separate systems?", tag: "THE OPERATIONS QUESTION", text: "Ask a vendor to demonstrate how staff move between schools and campuses, which data each role can see, and how cross-school oversight works. A shared login alone does not prove unified reporting. Validate the exact workflow with your own principal and administrators." },
  { title: "The questions to ask before you switch.", tag: "THE MIGRATION QUESTION", text: "Start with a sample of student and guardian records. Check field mapping, duplicates, access permissions and how you can retrieve your data. Agree on the scope of migration, support and any additional charges in writing before committing to a rollout." },
];

export default function Website() {
  const [role, setRole] = useState(0);
  const [students, setStudents] = useState(2000);
  const [rate, setRate] = useState(30);
  const [years, setYears] = useState(3);
  const [menu, setMenu] = useState(false);
  const [article, setArticle] = useState<number | null>(null);
  const person = personas[role];
  const comparison = students * rate * 12 * years;
  const flat = product.annualPrice * years;
  return <div className={styles.site}>
    <a className={styles.skip} href="#main">Skip to content</a>
    <header className={styles.header}>
      <a className={styles.logo} href="#" aria-label="Northstar School OS home"><span className={styles.mark}>✳</span> northstar<span className={styles.logoSuffix}>SCHOOL OS</span></a>
      <button className={styles.menuButton} aria-expanded={menu} aria-controls="website-nav" onClick={() => setMenu(!menu)}>{menu ? "Close" : "Menu"}</button>
      <nav id="website-nav" className={`${styles.nav} ${menu ? styles.navOpen : ""}`} aria-label="Main navigation">
        <a onClick={() => setMenu(false)} href="#tour">Tour the OS</a><a onClick={() => setMenu(false)} href="#compare">See the math</a><a onClick={() => setMenu(false)} href="#pricing">Pricing</a><a onClick={() => setMenu(false)} href="#perspectives">Perspectives</a>
      </nav>
      <a className={styles.navCta} href="#next-step">Plan your free trial <span>↗</span></a>
    </header>
    <main id="main">
      <section className={styles.hero}>
        <div className={styles.heroCopy}><p className={styles.eyebrow}>A NEW DIRECTION FOR SCHOOL MANAGEMENT</p><h1>Your school is<br/>going places.<br/><em>Your software<br/>should keep up.</em></h1><p className={styles.lede}>One connected operating system for the people who run your school. Less administrative friction. More room to grow.</p><div className={styles.actions}><a className={styles.primary} href="#tour">Meet your school’s new OS <span>↗</span></a><a className={styles.textLink} href="#compare">See the math <span>↓</span></a></div><p className={styles.heroNote}>Built around your school day. Designed for your next chapter.</p></div>
        <div className={styles.heroVisual}>
          <div className={styles.orbitLabel}>A LITTLE LESS ADMIN. A LOT MORE SCHOOL.</div>
          <div className={styles.preview}>
            <div className={styles.previewTop}><b>✳ northstar</b><span>School workspace</span><span className={styles.avatar}>NS</span></div>
            <div className={styles.previewBody}><div className={styles.previewSide}><span className={styles.sideActive}>◫</span><span>▦</span><span>☷</span><span>◷</span><span>⚑</span></div><div className={styles.previewContent}><div className={styles.previewHeading}><div><small>MONDAY, 16 SEPTEMBER</small><h2>A good day to move forward.</h2></div><span>↗</span></div><div className={styles.demoMetrics}><div><span>Students</span><b>1,248</b><small>One connected directory</small></div><div><span>Attendance</span><b>96.4<small>%</small></b><small>Today’s school view</small></div></div><div className={styles.week}><div><b>The week in view</b><span>Attendance</span></div><div className={styles.bars}>{[76,88,82,94,90].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{["Mon","Tue","Wed","Thu","Fri"][i]}</span></div>)}</div></div><div className={styles.previewTask}><span>✓</span><div><b>Class diary, done.</b><small>More time for what comes next.</small></div><span>↗</span></div></div></div>
          </div><div className={styles.visualCaption}><span>CONNECTED BY DESIGN</span><span>Illustrative product view · Sample data</span></div>
        </div>
      </section>
      <div className={styles.beliefStrip}><span>One school day.<br/><b>Everything connected.</b></span><span>People & attendance</span><span>Teaching & learning</span><span>Fees & operations</span><span>Families & communication</span></div>
      <section className={styles.section} id="tour"><div className={styles.sectionHead}><p className={styles.eyebrow}>BUILT AROUND PEOPLE, NOT MODULES</p><h2>Different responsibilities.<br/>One shared direction.</h2><p>Start with what matters to you. See how Northstar brings everyday work together.</p></div><div className={styles.roleTabs} aria-label="Choose your role">{personas.map((p,i)=><button key={p.name} aria-pressed={role===i} className={role===i?styles.selected:""} onClick={()=>setRole(i)}><span>0{i+1}</span>{p.name}<span>↗</span></button>)}</div><div className={styles.rolePanel} aria-live="polite"><div><h3>{person.title}</h3><p>{person.text}</p><ul>{person.points.map(point=><li key={point}><span>✓</span>{point}</li>)}</ul></div><div className={styles.rolePreview}><div className={styles.rolePreviewHead}><span>✳</span><b>{person.label}</b><small>Sample view</small></div><div className={styles.roleMetrics}>{person.metrics.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className={styles.roleRows}>{person.rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><p>Explore the workflow in the <a href="/prototype/index.html">interactive teacher prototype ↗</a></p></div></div></section>
      <section className={styles.features}><div className={styles.sectionHead}><p className={styles.eyebrow}>LESS FRICTION. MORE FORWARD.</p><h2>The everyday essentials.<br/>Finally, working together.</h2></div><div className={styles.featureGrid}>{product.capabilities.map(feature=><article key={feature.title}><span className={styles.featureNumber}>{feature.icon} <span>↗</span></span><p className={styles.eyebrow}>{feature.category}</p><h3>{feature.title}</h3><p>{feature.description}</p></article>)}</div><div className={styles.roadmap}><b>What’s next</b><span>{product.planned.join(" · ")}</span><small>Planned capabilities, not included in the current product.</small></div></section>
      <section className={styles.section} id="compare"><div className={styles.sectionHead}><p className={styles.eyebrow}>YOUR GROWTH SHOULDN’T BE A LINE ITEM</p><h2>More students.<br/>Do the math, not the guesswork.</h2><p>Compare a per-student quote with the proposed Northstar annual license. Use your own numbers.</p></div><div className={styles.calculator}><div className={styles.controls}><label htmlFor="students">Students across your schools <strong>{students.toLocaleString("en-IN")}</strong></label><input id="students" type="range" min="100" max="10000" step="100" value={students} onChange={e=>setStudents(Number(e.target.value))}/><div className={styles.rangeEnds}><span>100</span><span>10,000</span></div><div className={styles.numberControls}><label htmlFor="rate">Monthly cost per student (₹)<input id="rate" type="number" min="0" max="10000" value={rate} onChange={e=>setRate(Math.max(0,Math.min(10000,Number(e.target.value))))}/></label><label htmlFor="years">Years to compare<select id="years" value={years} onChange={e=>setYears(Number(e.target.value))}>{[1,3,5].map(y=><option key={y} value={y}>{y} {y===1?"year":"years"}</option>)}</select></label></div><p>Illustrative license comparison only. Assumes a constant student count and rate; excludes taxes, hosting, migration and other charges unless your final quote includes them.</p></div><div className={styles.results} aria-live="polite"><div><span>Per-student model · {years} {years===1?"year":"years"}</span><b>{rupees(comparison)}</b><i style={{width:`${Math.max(2,comparison/Math.max(comparison,flat)*100)}%`}}/></div><div><span>Northstar annual model · {years} {years===1?"year":"years"}</span><b>{rupees(flat)}</b><i style={{width:`${Math.max(2,flat/Math.max(comparison,flat)*100)}%`}}/></div><p>{comparison>=flat?<>Potential license savings <strong>{rupees(comparison-flat)}</strong></>:<>The per-student quote is lower by <strong>{rupees(flat-comparison)}</strong></>}</p></div></div></section>
      <section className={styles.pricing} id="pricing"><div className={styles.sectionHead}><p className={styles.eyebrow}>A PLAN FOR YOUR NEXT CHAPTER</p><h2>Predictable by design.</h2><p>Two proposed licensing models. Choose the approach that fits your institution.</p></div><div className={styles.priceGrid}><article><span className={styles.eyebrow}>THE ANNUAL LICENSE</span><h3>Room to grow.</h3><p>For schools that prefer predictable annual budgeting.</p><div className={styles.price}>{rupees(product.annualPrice)}<small>/ year</small></div><ul><li>Flat annual software license</li><li>Proposed unlimited student and staff access</li><li>Multi-branch scope agreed during onboarding</li><li>Migration and support scope confirmed in your quote</li></ul><a className={styles.primary} href="#next-step">Plan your evaluation <span>↗</span></a></article><article className={styles.perpetual}><span className={styles.eyebrow}>THE PERPETUAL LICENSE</span><h3>Think long term.</h3><p>For institutions that prefer a one-time license investment.</p><div className={styles.price}>{rupees(product.perpetualPrice)}<small>/ one time</small></div><ul><li>Proposed perpetual software license</li><li>License-cost crossover at approximately 3.3 years</li><li>Branch coverage confirmed in your agreement</li><li>Hosting, upgrades and support terms agreed separately</li></ul><a className={styles.primary} href="#next-step">Explore the long-term fit <span>↗</span></a></article></div><p className={styles.pricingNote}>Indicative pricing from the Northstar proposal. Final inclusions, taxes, service terms and trial availability require confirmation. No payment is collected here.</p></section>
      <section className={styles.section} id="perspectives"><div className={styles.sectionHead}><p className={styles.eyebrow}>A MORE INFORMED NEXT MOVE</p><h2>Good questions.<br/>Better decisions.</h2></div><div className={styles.articles}>{articles.map((a,i)=><button key={a.title} onClick={()=>setArticle(i)}><span>{a.tag}</span><h3>{a.title}</h3><b>Read the perspective ↗</b></button>)}</div>{article!==null&&<div className={styles.articleDetail} role="region" aria-label={articles[article].title}><button onClick={()=>setArticle(null)} aria-label="Close perspective">Close ×</button><h3>{articles[article].title}</h3><p>{articles[article].text}</p></div>}</section>
      <section className={styles.nextStep} id="next-step"><span className={styles.bigStar}>✳</span><div><p className={styles.eyebrow}>YOUR NEXT CHAPTER STARTS WITH A CLOSER LOOK</p><h2>See what a calmer<br/>school day could look like.</h2><p>Explore the teacher workflow with sample data. Then evaluate Northstar with the people who will use it every day.</p><a className={styles.primary} href="mailto:vinayraghavendran16@gmail.com?subject=Northstar%20School%20OS%20%E2%80%94%2030-day%20trial%20enquiry&body=Hello%20Northstar%2C%0A%0AI%20would%20like%20to%20discuss%20a%2030-day%20evaluation.%0ASchool%20name%3A%0AMy%20role%3A%0AStudent%20count%3A%0ANumber%20of%20branches%3A%0A">Discuss a 30-day free trial <span>↗</span></a><small>Opens your email app · We’ll confirm trial scope and availability together.</small></div></section>
    </main><footer className={styles.footer}><a className={styles.logo} href="#"><span className={styles.mark}>✳</span> northstar</a><span>A clearer direction for your school.</span><a href="mailto:vinayraghavendran16@gmail.com">Talk to Northstar ↗</a><span>© {new Date().getFullYear()} Northstar School OS</span></footer>
  </div>;
}
